DROP TABLE IF EXISTS TBL_PRODUCTS;
CREATE TABLE TBL_PRODUCTS (
    ID VARCHAR(5) NOT NULL,
    KIND VARCHAR(5) NOT NULL,
    PRODUCT_NAME VARCHAR(200) NOT NULL,
    PRICE NUMBER NOT NULL,
    STOCK NUMBER NOT NULL
);